/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openalpr_AlprJNIWrapper */

#ifndef _Included_org_openalpr_AlprJNIWrapper
#define _Included_org_openalpr_AlprJNIWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_openalpr_Alpr
 * Method:    initialize
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_openalpr_AlprJNIWrapper_initialize
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     org_openalpr_Alpr
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_openalpr_AlprJNIWrapper_dispose
  (JNIEnv *, jobject);

/*
 * Class:     org_openalpr_Alpr
 * Method:    is_loaded
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_openalpr_AlprJNIWrapper_is_1loaded
  (JNIEnv *, jobject);

/*
 * Class:     org_openalpr_Alpr
 * Method:    native_recognize
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_openalpr_AlprJNIWrapper_native_1recognize__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_openalpr_Alpr
 * Method:    native_recognize
 * Signature: ([B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_openalpr_AlprJNIWrapper_native_1recognize___3B
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_openalpr_Alpr
 * Method:    native_recognize
 * Signature: (JIII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_openalpr_AlprJNIWrapper_native_1recognize__JIII
  (JNIEnv *, jobject, jlong, jint, jint, jint);

/*
 * Class:     org_openalpr_Alpr
 * Method:    set_default_region
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_openalpr_AlprJNIWrapper_set_1default_1region
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_openalpr_Alpr
 * Method:    detect_region
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_openalpr_AlprJNIWrapper_detect_1region
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_openalpr_Alpr
 * Method:    set_top_n
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_openalpr_AlprJNIWrapper_set_1top_1n
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_openalpr_Alpr
 * Method:    get_version
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_openalpr_AlprJNIWrapper_get_1version
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
