/*
 * Stub for class sapphire.appexamples.hankstodo.app.TodoListManager
 * Generated by Sapphire Compiler (sc).
 */
package sapphire.appexamples.hankstodo.app.stubs;


public final class TodoListManager_Stub extends sapphire.appexamples.hankstodo.app.TodoListManager implements sapphire.common.AppObjectStub {

    sapphire.policy.SapphirePolicy.SapphireClientPolicy $__client = null;
    boolean $__directInvocation = false;

    public TodoListManager_Stub () {
        super();
    }


    public void $__initialize(sapphire.policy.SapphirePolicy.SapphireClientPolicy client) {
        $__client = client;
    }

    public void $__initialize(boolean directInvocation) {
        $__directInvocation = directInvocation;
    }

    public Object $__clone() throws CloneNotSupportedException {
        return super.clone();
    }



    // Implementation of newTodoList(String)
    public sapphire.appexamples.hankstodo.app.TodoList newTodoList(java.lang.String $param_String_1) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.newTodoList( $param_String_1);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public sapphire.appexamples.hankstodo.app.TodoList sapphire.appexamples.hankstodo.app.TodoListManager.newTodoList(java.lang.String)";
                $__params.add($param_String_1);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((sapphire.appexamples.hankstodo.app.TodoList) $__result);
    }

    // Implementation of dhtGetData()
    public java.util.Map dhtGetData() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.dhtGetData();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public java.util.Map<sapphire.policy.interfaces.dht.DHTKey, ?> sapphire.appexamples.hankstodo.app.TodoListManager.dhtGetData()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.util.Map) $__result);
    }
}
