/*
 * Stub for class net.lrstudios.android.pachi.PachiEngine
 * Generated by Sapphire Compiler (sc).
 */
package net.lrstudios.android.pachi.stubs;


import lrstudios.games.ego.lib.EngineContext;
import lrstudios.games.ego.lib.ui.GtpBoardActivity;

public final class PachiEngine_Stub extends net.lrstudios.android.pachi.PachiEngine implements sapphire.common.AppObjectStub {

    sapphire.policy.SapphirePolicy.SapphireClientPolicy $__client = null;
    boolean $__directInvocation = false;

    public PachiEngine_Stub (EngineContext $param_Context_1) {
        super($param_Context_1);
    }

    public void $__initialize(sapphire.policy.SapphirePolicy.SapphireClientPolicy client) {
        $__client = client;
    }

    public void $__initialize(boolean directInvocation) {
        $__directInvocation = directInvocation;
    }

    public Object $__clone() throws CloneNotSupportedException {
        return super.clone();
    }



    // Implementation of init(Properties)
    public boolean init(java.util.Properties $param_Properties_1) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.init( $param_Properties_1);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public boolean net.lrstudios.android.pachi.PachiEngine.init(java.util.Properties)";
                $__params.add($param_Properties_1);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.lang.Boolean) $__result).booleanValue();
    }

    // mnual patch: Implementation of sendGtpCommand(String)
    public String sendGtpCommand(String $param_Command_1) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.sendGtpCommand( $param_Command_1);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public java.lang.String lrstudios.games.ego.lib.ExternalGtpEngine.sendGtpCommand(java.lang.String)";
                $__params.add($param_Command_1);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return (java.lang.String) $__result;
    }

    // Implementation of getVersion()
    public java.lang.String getVersion() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getVersion();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public java.lang.String net.lrstudios.android.pachi.PachiEngine.getVersion()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.lang.String) $__result);
    }

    // Implementation of getName()
    public java.lang.String getName() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getName();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public java.lang.String net.lrstudios.android.pachi.PachiEngine.getName()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.lang.String) $__result);
    }
}
