/*
 * Stub for class org.openalpr.AlprSapphire
 * Generated by Sapphire Compiler (sc).
 */
package org.openalpr.stubs;


public final class AlprSapphire_Stub extends org.openalpr.AlprSapphire implements sapphire.common.AppObjectStub {

    sapphire.policy.SapphirePolicy.SapphireClientPolicy $__client = null;
    boolean $__directInvocation = false;

    public AlprSapphire_Stub () {
        super();
    }


    public void $__initialize(sapphire.policy.SapphirePolicy.SapphireClientPolicy client) {
        $__client = client;
    }

    public void $__initialize(boolean directInvocation) {
        $__directInvocation = directInvocation;
    }

    public Object $__clone() throws CloneNotSupportedException {
        return super.clone();
    }



    // Implementation of recognizeWithCountryRegionNConfig(String, String, String, String, int)
    public java.lang.String recognizeWithCountryRegionNConfig(java.lang.String $param_String_1, java.lang.String $param_String_2, java.lang.String $param_String_3, java.lang.String $param_String_4, int $param_int_5) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.recognizeWithCountryRegionNConfig( $param_String_1,  $param_String_2,  $param_String_3,  $param_String_4,  $param_int_5);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public java.lang.String org.openalpr.AlprSapphire.recognizeWithCountryRegionNConfig(java.lang.String,java.lang.String,java.lang.String,java.lang.String,int)";
                $__params.add($param_String_1);
                $__params.add($param_String_2);
                $__params.add($param_String_3);
                $__params.add($param_String_4);
                $__params.add($param_int_5);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.lang.String) $__result);
    }

    // Implementation of recognizeWithCountryNRegion(String, String, String, int)
    public java.lang.String recognizeWithCountryNRegion(java.lang.String $param_String_1, java.lang.String $param_String_2, java.lang.String $param_String_3, int $param_int_4) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.recognizeWithCountryNRegion( $param_String_1,  $param_String_2,  $param_String_3,  $param_int_4);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public java.lang.String org.openalpr.AlprSapphire.recognizeWithCountryNRegion(java.lang.String,java.lang.String,java.lang.String,int)";
                $__params.add($param_String_1);
                $__params.add($param_String_2);
                $__params.add($param_String_3);
                $__params.add($param_int_4);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.lang.String) $__result);
    }

    // Implementation of recognize(String, int)
    public java.lang.String recognize(java.lang.String $param_String_1, int $param_int_2) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.recognize( $param_String_1,  $param_int_2);
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public java.lang.String org.openalpr.AlprSapphire.recognize(java.lang.String,int)";
                $__params.add($param_String_1);
                $__params.add($param_int_2);
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.lang.String) $__result);
    }

    // Implementation of isOpenALPRNull()
    public boolean isOpenALPRNull() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.isOpenALPRNull();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public boolean org.openalpr.AlprSapphire.isOpenALPRNull()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.lang.Boolean) $__result).booleanValue();
    }

    // Implementation of create()
    public void create() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.create();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void org.openalpr.AlprSapphire.create()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
